# ============================================
# $Id: Makefile,v 1.1 2008/05/16 13:25:15 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
