# ============================================
# $Id: Makefile,v 1.2 2008/11/13 13:02:03 jerome Exp $
# ============================================


export targetdir
export utildir

include $(utildir)/PubRule

DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
